; Podglad stanu wejscia na zywo — test modulu MAX3232
[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.*usb*
monitor_port = /dev/cu.*usb*
