; Klawiatura Posnet -> klawiatura Bluetooth (BLE HID)
; ESP32-WROOM DevKit

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    https://github.com/T-vK/ESP32-BLE-Keyboard.git
upload_port = /dev/cu.*usb*
monitor_port = /dev/cu.*usb*
